version: "3"
volumes:
        node-modules-vue3:
services: 
        vue3:
                image: vue-cli3:0
                build:
                        context: .
                        dockerfile: Dockerfile
                container_name: vue3-cli
                ports:
                        - "8080:8080"
                volumes:
                        - "./app:/app"
                        - "node-modules-vue3:/app/cipher-app/node_modules"
                stdin_open: true
                tty: true

